#!/usr/bin/env sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

while :
do
    (cd $DIR&&python ../../clients/rl_client_ale.py --agent "$1")
    echo "Starting new client in 10 seconds. Press [CTRL+C] to cancel ..."
    sleep 10
done
