#!/usr/bin/env python
import sys
import imp

sys.path.append('/home/dennis/Projects/random_agent.runfiles/org_deepmind_lab')

# foo = imp.load_source('deepmind_lab',
#     '/home/dennis/Projects/random_agent.runfiles/org_deepmind_lab/tst.py')
# foo.run()

foo = imp.load_dynamic('deepmind_lab',
    '/home/dennis/Projects/random_agent.runfiles/org_deepmind_lab/deepmind_lab.so')

level = 'tests/my_map'
env = foo.Lab(
    level, ['RGB_INTERLACED'],
    config={
        'fps': str(20),
        'width': str(84),
        'height': str(84)
    })

env.reset()
